### ISSUE TITLE
Installing Recovery image with Ubuntu 22.04.2

### ISSUE THREAD

**Issue by LanHikari22** [LambdaLabs/lambda-docs#253]
Hi,

Currently the recovery image I installed via https://docs.lambdalabs.com/linux/recovery-images/ is lambda-recovery-jammy-20230704.iso. 

This is running Ubuntu 22.04.3 LTS. I was wondering if there is a recovery image for 22.04.2 LTS or if I can downgrade without risk.

Thanks,
Mohammed

**Comment by cbrownstein-lambda** [comment]
Hi Mohammed,

What are you trying to accomplish by using an older version of Ubuntu?

**Comment by LanHikari22** [comment]
It is a version used by the rest of my team, and since I am just setting up my system, I am trying to match their spec. I can also ask them to upgrade if critical. 

Thanks,
Mohammed

**Comment by cbrownstein-lambda** [comment]
Point releases such as 22.04.2 and 22.04.3 are just "snapshots" of the current Ubuntu packages at the time the snapshots were taken. See, for example, [this thread](https://askubuntu.com/questions/106159/what-are-point-releases-in-lts-versions) in Ask Ubuntu.

This means that if a system was initially set up with 22.04.2 then upgraded by running, for example, `sudo apt update && sudo apt dist-upgrade`, the system would have packages _at least as new as_ the packages part of 22.04.3. I say _at least as new as_ because packages likely have been upgraded since 22.04.3 was released.

If your team wants to maintain consistent environments, I suggest your team look at the following FAQs:

- [How do I create a conda virtual environment?](https://docs.lambdalabs.com/linux/create-conda-virtual-environment/)
- [How do I create a Python virtual environment?](https://docs.lambdalabs.com/linux/create-python-virtual-environment/)
- [How do I install Docker and run a container?](https://docs.lambdalabs.com/linux/install-docker-run-container/)

I'm closing this ticket as the Lambda [community forum](https://deeptalk.lambdalabs.com/) is a better place to have this discussion.

**Comment by LanHikari22** [comment]
Awesome, that's very informative. Thank you!
